### PR TITLE
Relay Color Pannel (Requires Configs for Relay and Fix RA-100 so it also points to the combined PNG)

### PR DESCRIPTION
**Pull request by EmberSkyMedia**

### CODE REVIEW

**Comment by Spartwo** [comment]
If this is a final mask I'd recommend exporting in dds format

**Comment by EmberSkyMedia** [comment]
Not 100% final, it "should be" but without configs I can't 100% confirm no errors as I still need configs and test in KSP (tested in Blender)

**Comment by likeproblem** [comment]
Looks good, @Spartwo do you want to commit configs to fork and test it? Or I should do it?

**Comment by EmberSkyMedia** [comment]
Blender Example (Black section will be default grey colour)
image

**Comment by likeproblem** [comment]
May I ask though what did you change with Ra 100? (I see you painted green over blue in corner)

**Comment by EmberSkyMedia** [comment]
RA-100 shouldn't have any changes to it, but given all the relays use the same Image, it doesn't need its own image.

**Comment by EmberSkyMedia** [comment]
Good eye, my bad... I'll fix it.

**Pull request closed without merging**
