### PR TITLE
Existing Assets

### PR DESCRIPTION
**Pull request by Spartwo**
Various Restock TURD assets and configs I've made over time

### CODE REVIEW

**Comment by Spartwo** [comment]
- DTS-M1 Antenna
- Transform names for Truss, IBeam, and Node Parts
- Non-DLC Panels
- Rapier
- Material bay
- Resizable Structural Tubes

**Comment by likeproblem** [comment]
Hello, there's a problem with configs. For some reason Default one have the same configs as Recolour one, which shouldn't happen
 
For example, Default should have ```MODULE{name = KSPTextureSwitch...}``` instead of ```MODULE[KSPTextureSwitch]{...}```

**Comment by Spartwo** [comment]
Bit of an oversight. Will fix

**Comment by likeproblem** [comment]
Hey, is it okay with you if I only pull textures and make configs from (almost) ground up? It is better yo create it from scratch then try to fix it

**Comment by Spartwo** [comment]
> Hey, is it okay with you if I only pull textures and make configs from (almost) ground up? It is better to create it from scratch then try to fix it

No

I'm just finished making configs

**Comment by Spartwo** [comment]
image

**Comment by UncleMateo** [comment]
Awesome work!

**Comment by UncleMateo** [comment]
Hey Spartwo, double check your _Paint/Recolor configs, I noticed a handful of parts with the 000_ precursor, but for the _Paint you need that part to start with 999_ or it won't load in the right order.  Didn't see any other issues on a quick skim.

**Comment by UncleMateo** [comment]
uh I guess the underscore does italics on this board
oops
Well you probably get the idea without them

**Comment by Spartwo** [comment]
> Hey Spartwo, double check your _Paint/Recolor configs, I noticed a handful of parts with the 000_ precursor, but for the _Paint you need that part to start with 999_ or it won't load in the right order. Didn't see any other issues on a quick skim.

Way ahead of you

**Comment by likeproblem** [comment]
Looks great and should be ready to merge! Thanks again for contribution, though some stuff is named differently, but I leave it as is.

@UncleMateo do we want to edit anything else or we merge now?

**Comment by UncleMateo** [comment]
Looks good to me.. Just in case, I made a local backup of the previous build.

**Comment by likeproblem** [comment]
I'll probably remove @name = ... additions, they can be implemented into TextureSets

**Pull request merged**
